### ISSUE TITLE
 爱奇艺失效

### ISSUE THREAD

**Issue by woniux** [KikoPlayProject/KikoPlay#101]
添加任何弹幕都显示0条

**Comment by Protostars** [comment]
我试了一下，应该没失效，可能确实没有弹幕，另外这类issue可以在[脚本仓库](https://github.com/KikoPlayProject/KikoPlayScript)提

**Comment by woniux** [comment]
> 您好，由于目前系统优化升级，部分视频暂时无法使用弹幕功能，您可在优化完成后再次使用此功能，感谢您对爱奇艺的支持！温馨提示：具体系统优化时间请您以前端显示为准。

原来是官方关闭了部分剧的弹幕按钮导致的。。
