### ISSUE TITLE
爲什麽我下載下來打開是英文的

### ISSUE THREAD

**Issue by arasakaxx** [KikoPlayProject/KikoPlay#103]
下載下來解壓縮完打開kikoplay.exe 我這樣的使用方式是不對的嗎？

![image](https://user-images.githubusercontent.com/119490232/212976332-4087250e-ca9a-41aa-af8f-aa8597f03723.png)

**Comment by Protostars** [comment]
系统语言非简体中文，默认就显示英文了，可以手动设置settings.ini中`KikoPlay/Language`为zh-CN

**Comment by arasakaxx** [comment]
可以了謝謝你
