### ISSUE TITLE
增加语言更改设置

### ISSUE THREAD

**Issue by CaptainRay1993** [KikoPlayProject/KikoPlay#105]
我Win11系统语言是英文，KikoPlay下载下来默认就是英文然后设置里没找到语言更改选项。

**Comment by Protostars** [comment]
有几个类似的了 https://github.com/KikoPlayProject/KikoPlay/issues/104

**Comment by CaptainRay1993** [comment]
好的，已解决，但还是希望在以后更新里直接在UI里可以设置。
