### ISSUE TITLE
libmpv 使用的是 x86_64-v3 将无法在老旧 CPU 上启用该程序

### ISSUE THREAD

**Issue by debugzxcv** [KikoPlayProject/KikoPlay#108]
> **Difference between x86_64 and x86_64-v3**
> x86_64-v3 build have these instructions enabled by default:
> 
> `avx avx2 bmi bmi2 fma lzcnt movbe sse3 sse4 sse4.1 sse4.2 ssse3 xsave sahf mwait crc32 cx16 popcnt f16c`
> Cpu which dont have these features will fail to launch the x86_64-v3 build

https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/#readme

**Comment by Protostars** [comment]
如果有条件，可以下载没有v3后缀的[libmpv](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/)，替换lib/x64下的libmpv.dll.lib，编译后使用没有v3后缀的libmpv附带的dll

**Comment by Protostars** [comment]
后面换回了之前版本的Libmpv
