### ISSUE TITLE
bug:仍然会关闭已有的aria2进程

### ISSUE THREAD

**Issue by FxxKZhangYue** [KikoPlayProject/KikoPlay#109]
kikoplay版本 0.9.3

settings.ini已经添加了以下内容

[Download]
KillExistAria2=false

但是kikoplay仍然在启动的时候关闭了本人的aria2进程

可不可以考虑修改kikoplay自带aria2c rpc的端口

**Comment by FxxKZhangYue** [comment]
每次启动kikoplay 都会修改airng的会话，预设的下载路径，参数都被kikoplay改了，能不能换个端口或者禁用aria2功能

**Comment by Protostars** [comment]
1.0.0增加了相关选项。另外你需要在KikoPlay关闭的时候修改settings.ini
