### ISSUE TITLE
建议：优化搜索功能

### ISSUE THREAD

**Issue by LSP0123** [KikoPlayProject/KikoPlay#110]
![image](https://github.com/KikoPlayProject/KikoPlay/assets/31061624/4ad19fc3-fad6-49a6-bf47-4399f2a1231a)
建议优化搜索功能，在搜索内输入空格后自动将当前输入内容转化为单个，如下：
![image](https://github.com/KikoPlayProject/KikoPlay/assets/31061624/051d1710-e95f-4eec-97e4-52e6ed1662b5)

**Comment by Protostars** [comment]
其他软件/网站有这样做吗，想看几个例子，

**Comment by LSP0123** [comment]
> 其他软件/网站有这样做吗，想看几个例子，

https://bangumi.moe/
番组萌是这样的

**Comment by Protostars** [comment]
场景不太一样，萌番组的搜索完全基于标签，KikoPlay中并不是这样，具体query由脚本处理
