### ISSUE TITLE
建议：修改角色页面跳转

### ISSUE THREAD

**Issue by LSP0123** [KikoPlayProject/KikoPlay#111]
bangumi获取剧集信息后，从角色页面跳转至网页时，跳转页面为http，建议修改至https
![image](https://github.com/KikoPlayProject/KikoPlay/assets/31061624/5b176fdf-2d52-40bd-a1f1-f61b82daa3f0)

**Comment by Protostars** [comment]
这是脚本控制的，你可以自己改一下 https://github.com/KikoPlayProject/KikoPlayScript/blob/master/library/bangumi.lua#L191
