### ISSUE TITLE
能否在按鍵直傳模式下直接取消kikoplay的快捷鍵?

### ISSUE THREAD

**Issue by Jay921027** [KikoPlayProject/KikoPlay#113]
![image](https://github.com/KikoPlayProject/KikoPlay/assets/133524232/607286bb-f309-41c4-9161-d868c4f544fe)
使用說明中提到，若kikoplay的快捷鍵與kikoplay有衝突，可以映射到其他按鈕解除衝突。
但更直觀的方式應該是直接全部禁用kikoplay的快捷鍵，直接拿mpv的input.conf過來用就好，就不用遇到一個改一個
謝謝

**Comment by Jay921027** [comment]
另外我也發現若以預設程式直接打開播放程式，直傳模式會失效，只有先開程式再選播放哪個檔案才有效，不確定是不是bug。

**Comment by Protostars** [comment]
目前不会禁用KIkoPlay自己的快捷键；修改设置之后点√保存

**Comment by kagurainroy** [comment]
我原来用MPV，习惯pgdwn=add chapter 1, pgup=add chapter -1。
kikoplay占用了这两个键作为切换播放列表，怎么都习惯不来，也禁用不了内置的快捷键，修改按键映射只是让input.conf里面的键位变了……
希望内置快捷键可以修改键位或者直接禁用
自己编译kikoplay可以解决此问题吗？
