### ISSUE TITLE
选择视频质量

### ISSUE THREAD

**Issue by trimechee** [KikoPlayProject/KikoPlay#114]
您好，非常感谢您提供这个非常棒的软件！ 🥇 💯 

请，我有一个请求：添加一个选项来选择视频质量，例如在 youtube、ok.ru/video ..... 等平台上，因为有时互联网连接会变弱并且播放会出现抖动，非常感谢 :)

**Comment by Protostars** [comment]
kikoplay是本地视频播放器，你是通过url来播放网络视频吗

**Comment by trimechee** [comment]
@Protostars 是的，Kikoplay 是一个本地视频播放器，也是一个通过 url 的流媒体视频播放器，我能够播放来自 youtube、ok.ru/video 的视频...我们希望有一个选项可以选择质量视频：标准质量 360p、480p、高清 720p、全高清 1080p、4K......

**Comment by trimechee** [comment]
一位开发人员非常好心地告诉我美妙的 Uosc 的存在，这对于初学者和人群来说，使我们心爱的 KikoPlay 更加容易和简单地使用本机添加此程序将是很棒的，并且它将允许初学者轻松选择 想要的流媒体视频质量，非常感谢！

适用于 MPV 播放器的功能丰富、简约、基于接近的 UI：

https://github.com/tomasklaen/uosc

**Comment by Protostars** [comment]
可以通过yt-dlp下载，选择视频质量

**Comment by trimechee** [comment]
Great ! Thank you o much :) 💯 🥇
