### ISSUE TITLE
添加 yt-dlp、curl streamlink  和内部浏览器以浏览和下载更多网站并检测隐藏的嵌入视频

### ISSUE THREAD

**Issue by trimechee** [KikoPlayProject/KikoPlay#115]
出色的 KikoPlay 允许通过 aria2c 下载种子，这太棒了，我们非常感谢你:)

我们心爱的KikoPlay已经允许您直接从许多中文网站导航和下载，这真是太棒了，非常感谢！ ！

请我有一个请求：添加著名的“yt-dlp”下载器：

https://github.com/yt-dlp/yt-dlp

下载更多网站！

和 streamlink 用于直播 !
https://streamlink.github.io/
https://github.com/streamlink/streamlink
https://github.com/LaneSh4d0w/query-streamlink
https://github.com/keystroke3/query-streamlink
https://github.com/keystroke3/linkastream
https://github.com/back-to/liveproxy
https://github.com/back-to/generic

我还发现这个程序有一个原创和智能的概念：制作一个网络浏览器，其中本地集成了必要的工具来下载流媒体视频，因此不需要添加扩展程序，并且我们避免了有时禁止附加扩展程序的商店的审查......

VCap 下载器 (VCapDL)

https://vcapdl.com/

不幸的是，该程序在 30 天后就会受到限制，您甚至无法再下载标准 480p 视频......

这个下载器集成了curl：

https://curl.se/

https://github.com/kanishka-linux/hlspy

以及 ffmpeg 和其他工具来实现流媒体视频的顺利下载，我们知道这是非常复杂和困难的，但我们希望，如果技术上可行的话，拥有来自更多不同站点的集成下载器聚合器将是非常棒的，谢谢 多你啊！

此外，她的一些开源扩展插件和脚本可以帮助通过我们心爱的美丽的 KikoPlaye 下载视频，以检测更多的嵌入视频，如果没有网络浏览器插件扩展，则难以检测和下载：

https://www.downthemall.org/

https://github.com/rowrawer/stream- detector
https://github.com/chandler-stimson/live-stream-downloader
https://github.com/meowcateatrat/elephant

https://github.com/inbasic/bulk-media-downloader/

https://github.com/zaidka/cliget

https://openvideofs.github.io/
多米尼克·桑德
OpenVideo – 无广告流媒体
https://addons.mozilla.org/fr/firefox/addon/openvideo/
https://chrome.google.com/webstore/detail/openvideo-%E2%80%93-ad-free-strea/dadggmdmhmfkpglkfpkjdmlendbkehoh/support

     脚本

https://github.com/Momo707577045/media-source-extract

https://greasyfork.org/en/scripts/445751-unlimited-downloader

Youtube 工具 多合一本地下载 MP4、MP3 高品质，无需外部服务等。

https://greasyfork.org/fr/scripts/460680-youtube-tools-all-in-one-local-download-mp3-mp4-higt-quality-return-dislikes-and-more

https://greasyfork.org/fr/scripts/423851-simple-youtube-age-restriction-bypass

https://greasyfork.org/fr/scripts/369400-local-youtube-downloader

https://greasyfork.org/fr/scripts/434936-%E5%B1%8F%E8%94%BD%E6%89%80%E6%9C%89youtube%E5%B9%BF%E5%91%8A -youtube-广告拦截器-拦截所有广告，包括拦截-youtube-音乐

https://greasyfork.org/fr/scripts/34613-youtube-multi-downloader-yt1s-com-mp3-fhd-mp4-hd-sd-3gp-no-ads

YouTube-工具-扩展

https://github.com/DeveloperMDCM/Youtube-tools-extension

https://github.com/DeveloperMDCM/Youtube-tools-extension

https://github.com/dabaisuv/Tampermonkey-Script
https://greasyfork.org/fr/users/901788-dabaisuv
Unlimited_downloader by dabaisuv
https://greasyfork.org/fr/scripts/445751-unlimited-downloader
https://www.v2ex.com/t/856510
https://github.com/Momo707577045/m3u8-downloader/blob/master/README-EN.md
https://github.com/Momo707577045/media-source-extract

https://greasyfork.org/fr/scripts/445751-unlimited-downloader/discussions/153131
https://greasyfork.org/en/scripts/420325-mse-dump-tools
https://greasyfork.org/en/users/724921-tgsan
https://greasyfork.org/en/scripts/18671-inject2download
https://github.com/acolwell/mse-tools
https://github.com/acolwell/msetools-js
https://segmentfault.com/a/1190000025182822
https://github.com/Momo707577045/tinypng-script-with-cache
https://github.com/Momo707577045
https://github.com/kanishka-linux/hlspy
https://github.com/selsta/hlsdl
https://github.com/video-dev/hls.js

编辑：有一个使用qt6的很棒的工具，也许它可以帮助集成curl或其他工具来抓取和检测更多链接并嵌入复杂的视频......

https://github.com/kanishka-linux/hlspy

“一个基于 QtWebEngine (Chromium) 作为后端的简单无头浏览器

主要目标是创建类似于基于终端的实用程序但适用于 javascript 的网页的 curl/wget 。 不过，它也可以用作异步访问动态网页的 Python 库。”

**Comment by Protostars** [comment]
目前有个扩展app支持yt-dlp下载，你可以试试
