### ISSUE TITLE
用于本地播放和 YouTube 流媒体视频的纯音频模式

### ISSUE THREAD

**Issue by trimechee** [KikoPlayProject/KikoPlay#116]
您好，再次感谢您提供这个令人惊叹的精彩媒体播放器！ 和下载器 🥇💯

我请求仅对 YouTube 音频进行设置以支持专用音频流（如果可用），因此我们希望在 KikoPlay 中具有此功能，因为我经常睡觉并将电视节目、纪录片和播客的地址 url 放入播放列表中 媒体播放器，节省数据、电池和电量，避免风扇运转、发出噪音并吵醒我，并防止屏幕在夜间无法保持启用状态，如果 KikoPlay 具有用于从 YouTube 流式传输视频的纯音频模式，那就太好了 甚至可以从其他流媒体平台（如果有）！ 太感谢了 ：）

同样，我喜欢听电视节目......我从流媒体网站（与 youtube 不同的其他网站）将它们下载为 MP4，但我只想在睡觉时听音频，这样我的电脑屏幕就保持关闭状态 并且消耗的资源更少，神奇的KikoPlay能否在主界面添加一个选项或轻松访问按钮，一键关闭视频，从而只听本地下载视频的音频？ 非常感谢 ！

**Comment by szdytom** [comment]
If you use yt-dlp to download, you can pass `--format mp3` to download audio files only. Refer to <https://github.com/yt-dlp/yt-dlp#format-selection>

**Comment by trimechee** [comment]
Great ! Thank you so much @szdytom :) 💯 🥇
