### ISSUE TITLE
Mac 編譯失敗

### ISSUE THREAD

**Issue by sky456757** [KikoPlayProject/KikoPlay#117]
嘗試用mac編譯失敗，錯誤訊息如下

ld: library not found for -lmpv
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [KikoPlay.app/Contents/MacOS/KikoPlay] Error 1
make[1]: *** [CMakeFiles/KikoPlay.dir/all] Error 2
make: *** [all] Error 2

**Comment by Protostars** [comment]
可能你需要先装libmpv
