### ISSUE TITLE
在非全屏下弹幕滚动有点掉帧

### ISSUE THREAD

**Issue by recycle007** [KikoPlayProject/KikoPlay#118]
全屏下没问题，但非全屏下总感觉滚一会掉下帧，弹幕会抖一下，在话题搜了下加入Sampler2DArray=false还是没有解决

**Comment by Protostars** [comment]
Sampler2DArray=false 是解决a卡弹幕花屏的问题的。非全屏尝试缩小窗口大小，也还会掉帧吗

**Comment by recycle007** [comment]
> Sampler2DArray=false 是解决a卡弹幕花屏的问题的。非全屏尝试缩小窗口大小，也还会掉帧吗

无论是标准化窗口还是最大化窗口滚一会都会抖一下。。其实全屏细看好像也会，只是很不明显，基本可以忽略

**Comment by Protostars** [comment]
硬件配置怎么样，另外mpv有使用什么设置吗

**Comment by recycle007** [comment]
> 硬件配置怎么样，另外mpv有使用什么设置吗

i56500+1060，mpv参数没动过

**Comment by recycle007** [comment]
![捕获](https://github.com/KikoPlayProject/KikoPlay/assets/82096497/c18f6133-a468-4113-b51d-0f15013f4b7c)
找到原因了，很早以前因为n卡颜色泛白在网上找了教程这样自定义设置过，换回本机设置就不掉帧了。。。

**Comment by recycle007** [comment]
![捕获](https://github.com/KikoPlayProject/KikoPlay/assets/82096497/6ab2ef0a-f0bc-42f4-943a-fdd8a5ee3e3a)
找到原因了，很早以前因为n卡颜色泛白问题找的教程这样自定义设置过，换回改之前的本机设置就不掉帧了。。。
