### ISSUE TITLE
Impossible to play videos from my.mail.ru/video

### ISSUE THREAD

**Issue by trimechee** [KikoPlayProject/KikoPlay#119]
Hello, thank you so much for this amazing and awesome player and downloader ! 🥇 💯 

Please i have request, this famous website has many streaming videos and i wish to play videos from 

https://my.mail.ru/video

with our beloved KikoPlay but KikoPlay can't play this video from mail. ru, we hope there will be fix for this problem to be able to enjoy videos from this site without heavy web browser ! Thank you so much !

https://my.mail.ru/v/topclips/video/alltop/68528.html

Possible solution : what i can confirm is a lot of media players which can use yt-dlp like moon player, kikoplay, smplayer, mpc qt.....can't play videos from mail. ru, i have may be solution, see the source code or contact the developer of the magnificent GridPlayer which can play mail.ru videos, because I contacted him last year and he solved the problem and we can watch the videos from https://my.mail.ru/video with GridPlayer, and also with using "3DYD Youtube Source" with mpc-be mpc-hc and potplayer, so maybe the wonderful Grid Player developer Mr vzhd1701 could help !

Also the developer of QMPLAYER2 tells me that the next version of QMPLAY2 will fix this bug !

https://github.com/zaps166/QMPlay2

https://github.com/vzhd1701/gridplayer/issues/54

https://ys.3dyd.com/

**Comment by trimechee** [comment]
Hell, may be if it can help... yesterday the new version of QMPLAY2 media player has been published and the developer solved the problem of video playback from the site https://my.mail.ru/ :

https:// github.com/zaps166/QMPlay2/releases/tag/23.10.22

**Comment by Protostars** [comment]
这种网站需要yt-dlp等工具

**Comment by trimechee** [comment]
Yes but i tried with many media players which integrate yt-dlp, often impossible to play the video from this site except that I reported the problem to a developer who fixed this problem in his media player... it seems to me the latest version of KikoPlay integrates yt-dlp....
