### ISSUE TITLE
 add webtorrent feature

### ISSUE THREAD

**Issue by kawuwa** [KikoPlayProject/KikoPlay#120]
Can you add webtorrent feature?
[webtorrent](https://github.com/webtorrent/webtorrent)

**Comment by Protostars** [comment]
如果要下载种子，aria2已经可以了吧

**Comment by kawuwa** [comment]
but I also look forward to playing a torrent while downloading...

**Comment by kawuwa** [comment]
> 如果要下载种子，aria2已经可以了吧

but I also look forward to playing a torrent while downloading...

**Comment by Protostars** [comment]
边下边播目前没有考虑支持，短时间应该也很难，因为这对于一个本地弹幕播放器不太重要

**Comment by trimechee** [comment]
Webtorrent use webrtc, it uses a new revolutionary protocol that can be even more fluid and fast .....

Maybe these open source projects and media players can be an inspiration to add other features ton play streaming torrents whithout full donwloading them .....




https://ferrolho.github.io/magnet-player/
https://github.com/ferrolho/magnet-player
https://github.com/ThaUnknown/miru
https://powder.media/
https://github.com/PowderTech/PowderPlayer
https://github.com/popcorn-official/popcorn-desktop
https://popcorntime.app/
https://thaunknown.github.io/?miru
https://thaunknown.github.io/?pwa-haven
https://github.com/ThaUnknown/miru
https://github.com/Belfagor2005/MovieBrowser
https://github.com/saikou-app/saikou
https://github.com/Fmaldonado6/Akiyama
https://tachiyomi.org/forks/Neko/#neko
https://tachiyomi.org/forks/TachiyomiJ2K/
https://github.com/anime-android/CloudStream-3
