### ISSUE TITLE
[应用程序无法正常启动0xc0000142]

### ISSUE THREAD

**Issue by luquggg** [KikoPlayProject/KikoPlay#121]
搜了一圈没找到好的解决办法。
旧版本的试了下，从0.9.3开始都会出错，0.9.2可以启动

**Comment by Protostars** [comment]
0.9.3使用了新的libmpv，旧处理器可能不支持了 https://github.com/KikoPlayProject/KikoPlay/issues/108

**Comment by luquggg** [comment]
多谢解答。这真是有点遗憾

**Comment by Protostars** [comment]
如果有条件，可以下载没有v3后缀的libmpv(https://sourceforge.net/projects/mpv-player-windows/files/libmpv/)，替换lib/x64下的libmpv.dll.lib，编译后使用没有v3后缀的libmpv附带的dll
