### ISSUE TITLE
Play automatically videos from clipboard via shortcut CTRL + V

### ISSUE THREAD

**Issue by trimechee** [KikoPlayProject/KikoPlay#122]
Hello, it will be great to add  keyboard shortcut " CTRL + V " to quickly detect and play videos automatically from the clipboard, and we also hope our beloved KikoPlay will be compatible with this famous extension to quickly playback or download youtube videos in one click , thank you so much !

https://github.com/andy-portmen/external-application-button/

https://webextension.org/listing/external-application-button.html

"The "External Application Button" enhances your browser by providing a toolbar button and customizable context menu items. These features allow you to send page parameters such as page links, selected text, video, audio, and image source URLs to an external application. For example, you can use this extension to open the current page in a different browser or send an image to an external photo editor such as GIMP, Paint.net, or Photoshop. This action can happen by pressing a convenient context-menu item."

**Comment by Protostars** [comment]
目前需要先添加url到播放列表

**Comment by trimechee** [comment]
Great ! Thank you so much for your precious help 💯
