### ISSUE TITLE
能不能支持下实现网页点击唤醒播放功能

### ISSUE THREAD

**Issue by bitxeno** [KikoPlayProject/KikoPlay#123]
这样方便在jellyfin这样的媒体管理器中唤醒播放，希望能支持下传入字幕url和弹幕url

**Comment by Protostars** [comment]
目前是支持通过命令行打开文件/url的

**Comment by bitxeno** [comment]
命令行在网页用不了，好像是要注册一个专用的唤醒协议：https://blog.csdn.net/weixin_38080573/article/details/131216526

**Comment by Protostars** [comment]
目前暂时不考虑加这个功能
