### ISSUE TITLE
菜单快捷键改进建议

### ISSUE THREAD

**Issue by proItheus** [KikoPlayProject/KikoPlay#130]
![图片](https://github.com/KikoPlayProject/KikoPlay/assets/50539150/918ac420-a6f7-4f4a-8387-d96f8fee295e)
在这种多选菜单里，可以用方向键来高亮特定的选项，但是好像没办法用键盘切换选择状态。比如当高亮一个选项时，用回车切换选择状态。

主要是因为复选框在高分屏上太小了，鼠标一个一个点实在是……

**Comment by proItheus** [comment]
另一个相关的问题是`确定`和`取消`按钮太小了，比较难点到，希望能改成大一点的按钮 (也可能是我qt主题的问题？)

以及建议给`确定`也加个快捷键，比如`ctrl+enter`之类的

**Comment by kafovin** [comment]
复选框切换的快捷键，可以试一下使用"空格"键，我这边可以直接用空格切换选中和取消选中的状态。

**Comment by Protostars** [comment]
1.0.3做了改进，右键菜单能直接勾选选中的条目
