### ISSUE TITLE
[FR]增加在自动关联中忽略特定目录的功能

### ISSUE THREAD

**Issue by proItheus** [KikoPlayProject/KikoPlay#131]
我目前想到的，一种是类似于`.gitignore`那种在每个目录里分别放一个忽略模式的文件，另一种是全局的忽略模式设置。

使用场景：对于这种目录结构
```
anime
- cd
- - cd1
- - cd2
- sp
- ep1
...
```
自动关联总是会给`cd`，`sp`里的演唱会，声优访谈之类的关联奇怪的剧集，我想让自动关联忽略这种目录

**Comment by Protostars** [comment]
这个感觉可以加，我考虑一下

**Comment by Protostars** [comment]
1.0.1已加
