### ISSUE TITLE
Linux 系统下观看视频时会自动息屏

### ISSUE THREAD

**Issue by szdytom** [KikoPlayProject/KikoPlay#134]
在看视频的过程中, 电脑无操作时间达到电源管理锁屏及关闭屏幕的时间阈值时, 会执行相应的操作, 此时视频及声音照常播放, 移动鼠标唤醒电脑后恢复正常。

环境信息：

- GNU/Linux x86_64 6.6.7
- Gnome Desktop 44.0
- Kikoplay 1.0.0 (来自 [AUR](https://aur.archlinux.org/packages/kikoplay))

这个问题似乎是 #29 的功能回归，因为其在 2020/10/28 被标记为已完成。

Regression #29

**Comment by szdytom** [comment]
我没有很多 Qt 开发经验，但是似乎可以使用如下代码禁用屏幕保护：

```cpp
QScreen *screen = QGuiApplication::primaryScreen();
screen->setScreenSaverEnabled(false);
```

**Comment by Protostars** [comment]
Qt的文档里没有找到`setScreenSaverEnabled`这个函数，我不确定能否实现你要的效果，你可以改一下这里试试https://github.com/KikoPlayProject/KikoPlay/blob/master/UI/player.cpp#L1896

**Comment by szdytom** [comment]
不好意思，我找到的是错误的文章，确实没有 `setScreenSaverEnabled` 函数，不过我使用 D-Bus API 实现了这个功能（#135）。
