### ISSUE TITLE
建议增加手动导入本地xml弹幕文件的功能

### ISSUE THREAD

**Issue by burpheart** [KikoPlayProject/KikoPlay#138]
有些直播录播软件，比如录播姬，也会生成B站标准xml弹幕文件。
与普通视频不同的是，在这种情景下，并不需要弹幕池管理功能。
弹幕文件的使用方式类似于字幕，可以在当前播放的文件下通过手动选择本地xml或使用下载链接进行加载。

**Comment by Protostars** [comment]
这个功能，从第一个版本开始就有
