### ISSUE TITLE
关于软件图标的建议

### ISSUE THREAD

**Issue by Packer-Feng** [KikoPlayProject/KikoPlay#140]
能否在原有的图标基础上增加白底
现有的图标背景是透明的，在桌面背景为深色时不太明显

**Comment by madoka773** [comment]
https://github.com/flathub/io.github.KikoPlayProject.KikoPlay/blob/master/io.github.KikoPlayProject.KikoPlay.png

**Comment by Protostars** [comment]
可以自行替换一下快捷方式的图标

**Comment by Packer-Feng** [comment]
好的，谢谢，我需要关闭这个问题吗
