### ISSUE TITLE
kikoplay是不是video-sync无法调整？

### ISSUE THREAD

**Issue by kagurainroy** [KikoPlayProject/KikoPlay#142]
尝试添加 video-sync=display-resample 似乎无变化，是固定使用 video-sync=audio 吗？
另外 script-binding stats/display-stats-toggle 第二页为空白，可以实现 Show frame timings 吗？还是 libmpv 本身就这样？

**Comment by Protostars** [comment]
video-sync应该没有固定；翻页似乎没办法实现，和libmpv有关

**Comment by szdytom** [comment]
是否有证据证明在那个mpv选项框内填写任何东西会有效果？上次我填写了一些别的选项，似乎也没有生效

**Comment by kagurainroy** [comment]
> 是否有证据证明在那个mpv选项框内填写任何东西会有效果？上次我填写了一些别的选项，似乎也没有生效

什么选项框？你是说video-sync吗，我在mpv-lazy里用display-resample和audio是有区别的，用kiko检查不出来

**Comment by szdytom** [comment]
@kagurainroy 我在Settings-MPV Param里添加了 `auto-window-resize=no`，但是每次切换视频时，Kiko还是会调整窗口大小

**Comment by kagurainroy** [comment]
> @kagurainroy 我在Settings-MPV Param里添加了 `auto-window-resize=no`，但是每次切换视频时，Kiko还是会调整窗口大小

这个大概是因为libmpv的原因，嵌入在kikoplay里，部分设置是无效的，我自己在MPV参数里添加了一些参数，是可以正常用的

```
audio-file-auto=fuzzy
audio-channels=stereo
vf=vapoursynth="portable_config/vs/rife_danmuku.vpy"
hwdec=auto-copy
hwdec-codecs=all
hr-seek-framedrop=no
glsl-shaders=D:\mpv-lazy\portable_config\shaders\CfL_Prediction.glsl;D:\mpv-lazy\portable_config\shaders\Anime4K_Clamp_Highlights.glsl;D:\mpv-lazy\portable_config\shaders\Anime4K_Restore_CNN_soft_M.glsl;D:\mpv-lazy\portable_config\shaders\ravu_zoom_ar_r3_rgb.glsl
slang=chs,sc,zh-cn,chi,zh,zh-tw,cht,zho,ze
sub-font=LXGW WenKai Mono
sub-auto=fuzzy
input-conf=D:\mpv-lazy\portable_config\input_kiko.conf
osd-font-size=24
```

**Comment by Protostars** [comment]
> @kagurainroy 我在Settings-MPV Param里添加了 `auto-window-resize=no`，但是每次切换视频时，Kiko还是会调整窗口大小

视频播放区域右上角 窗口大小 选 固定
