### ISSUE TITLE
建议将媒体右键菜单的“添加”一栏上移到“播放”于“关联”之间

### ISSUE THREAD

**Issue by L-Ziting** [KikoPlayProject/KikoPlay#143]
建议将媒体右键菜单的“添加”一栏上移到“播放”于“关联”之间。因为本人看番都是手动添加视频文件或者URL，然后关联弹幕池，再添加弹幕，现在“添加”一栏在“关联”和“弹幕”的下面总是很变扭。。。
![屏幕截图 2024-02-07 005509](https://github.com/KikoPlayProject/KikoPlay/assets/154045571/0dd88bd6-d9bb-4b16-a55c-9ead0753e35b)

**Comment by Protostars** [comment]
后面可以改改

**Comment by Protostars** [comment]
1.0.2已修改
