### ISSUE TITLE
xml本地弹幕读取问题和一个列表优化建议

### ISSUE THREAD

**Issue by TtbqSora** [KikoPlayProject/KikoPlay#145]
1、B站下载的xml弹幕文件有时候会包含乱码字符，播放器读取到含有乱码字符的那一条弹幕后会停止读取，导致后续时间线的弹幕全部丢失，能否修改一下，比如跳过乱码这一条弹幕继续读取？之前使用弹弹play是可以的
![QQ截图20240222132948](https://github.com/KikoPlayProject/KikoPlay/assets/32391008/7ed81634-54f6-44df-a893-dcc617e8c8dd)
![QQ截图20240222132936](https://github.com/KikoPlayProject/KikoPlay/assets/32391008/761bf74c-c8c3-4dc4-ab5c-9c3fe1e787e6)
![QQ图片20240222132917](https://github.com/KikoPlayProject/KikoPlay/assets/32391008/490d20c3-b6e3-417b-b670-8a553cfc12fe)

2、另外媒体列表可否按文件夹区分一下，个人有囤货的习惯，一部番可能会存多个不同源的视频文件，导致在播放界面的媒体列表下出现大量重复，同时在资料页面，不同源的同一部番剧也完全被合并，导致播放的时候要不停手动跳过重复集，也不知道这个地方能不能手动修改？
![QQ截图20240222133318](https://github.com/KikoPlayProject/KikoPlay/assets/32391008/636326f4-ed9c-4b77-8965-dcc7b6fdc2c5)
![QQ截图20240222133309](https://github.com/KikoPlayProject/KikoPlay/assets/32391008/966c41a2-84f6-4eff-908e-ed24e5a438c6)
![QQ截图20240222133134](https://github.com/KikoPlayProject/KikoPlay/assets/32391008/2e888a5b-7fcb-494e-9df7-d1c62198afe5)

**Comment by Protostars** [comment]
1、后续会考虑调整
2、可以取消自动关联或者针对一些文件/目录跳过。默认关联成功的话，如果播放列表里有对应番组集合，KikoPlay会自动整理

**Comment by szdytom** [comment]
乱码字符是否是下载器的问题？b站的comment源的弹幕服务器配置的压缩策略很奇怪，至少在用 curl 下载时，需要添加 `--compressed` 才能正确解码

**Comment by Protostars** [comment]
1.0.2优化了读取本地弹幕文件的逻辑，容忍一定的错误
