### ISSUE TITLE
希望能够支持挂载alist

### ISSUE THREAD

**Issue by walltes** [KikoPlayProject/KikoPlay#146]

**Comment by Protostars** [comment]
能详细说明下吗

**Comment by Protostars** [comment]
如果是封装一下alist命令行客户端，感觉可以为KikoPlay开发一个扩展App

**Comment by walltes** [comment]
> 能详细说明下吗

类似potplayer，通过webdav挂载alist，将网盘文件添加到播放列表，然后就可以用播放器直接播放网盘里的视频。
<img width="1138" alt="HaJsWb0xgt" src="https://github.com/KikoPlayProject/KikoPlay/assets/129079223/c584537e-b410-465e-9237-2f77fb09c7f4">
<img width="770" alt="Rync4jQuUg" src="https://github.com/KikoPlayProject/KikoPlay/assets/129079223/4a028582-21a5-448b-86b8-591435e4bdf8">

**Comment by Protostars** [comment]
1.0.2播放列表支持添加webdav合集，可以试试

**Comment by walltes** [comment]
> 1.0.2播放列表支持添加webdav合集，可以试试

添加webdav合集时，对于多级目录只能添加到下一级目录内容
![image](https://github.com/KikoPlayProject/KikoPlay/assets/129079223/f37dc6e5-3a27-442b-8d62-1be968a39285)
![image](https://github.com/KikoPlayProject/KikoPlay/assets/129079223/6e099403-7ccf-4657-a610-d0915563b081)

**Comment by Protostars** [comment]
> > 1.0.2播放列表支持添加webdav合集，可以试试
> 
> 添加webdav合集时，对于多级目录只能添加到下一级目录内容，希望可以优化一下。 ![image](https://private-user-images.githubusercontent.com/129079223/318252831-f37dc6e5-3a27-442b-8d62-1be968a39285.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTM2MDEsIm5iZiI6MTcxMjU5MzMwMSwicGF0aCI6Ii8xMjkwNzkyMjMvMzE4MjUyODMxLWYzN2RjNmU1LTNhMjctNDQyYi04ZDYyLTFiZTk2OGEzOTI4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxNjIxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmZiMTc5Yjk4ZjcyMDUzNTQ5YTU5YTBhOTg5NDkyNDU2MWQ1Y2JlMTA0ZDBmNGJlZWFkY2U2NThjNTEwNzIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._7ZDibQIfUpJ9KewPs7v7gB-yEGioBboLUoKVxuUPXo)
> 
> ![image](https://private-user-images.githubusercontent.com/129079223/318254345-a5089f36-75a1-463d-be72-b9c8d8f17aec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTM2MDEsIm5iZiI6MTcxMjU5MzMwMSwicGF0aCI6Ii8xMjkwNzkyMjMvMzE4MjU0MzQ1LWE1MDg5ZjM2LTc1YTEtNDYzZC1iZTcyLWI5YzhkOGYxN2FlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxNjIxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWI3NTIwNDg4ZTZkOTZjYmZiOGRkZjFlMzgwOTY2N2VlNzE2NjUwOThhZTk3YjE5YjFlNzNjODlmMDgzZDQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j9jk0cEPm67p4hbIH_hQRHrkY0SL61IjS2ADlCm9mt0)

双击条目或者右键菜单扫描改动
