### ISSUE TITLE
希望在“资源搜索”结果中可以增加点击标题栏排序功能，感谢！

### ISSUE THREAD

**Issue by merlin0531** [KikoPlayProject/KikoPlay#150]
![)_GEY9EUY46A`%%H$@9_U71](https://github.com/KikoPlayProject/KikoPlay/assets/77084268/05e6774e-e71f-4d19-a83f-7d334f650def)
希望在“资源搜索”结果中可以增加点击标题栏排序功能，这样比较容易筛选出同一翻译小组的作品方便下载。如果能添加每页显示多少结果选项就更好了。（下载完成和全部任务中都可排序）

**Comment by Protostars** [comment]
1.0.3已增加
