### ISSUE TITLE
能否改进设置里下载上传规则。

### ISSUE THREAD

**Issue by merlin0531** [KikoPlayProject/KikoPlay#151]
目前下载 是等做种完成才会自动加入播放列表，能不能改成下载完就自动加入播放列表，而不是上传完成。但为了体现P2P共享精神是不是可以附加两个选择一个是做种满足上传下载量一定倍数如：1.2倍。或做种多长时间。个人到希望是下载完只要任务不删除可以限速一直上传。而不是任务完成就不再上传了。

**Comment by Protostars** [comment]
可以考虑

**Comment by Protostars** [comment]
1.0.3做了修改，可以再试试
