### ISSUE TITLE
linux 下 cmake 编译错误，Lua 源文件目录位置未更新，缺少Qt5WebSockets

### ISSUE THREAD

**Issue by zerobikappa** [KikoPlayProject/KikoPlay#152]
(1)
https://github.com/KikoPlayProject/KikoPlay/blob/d0437da99436313f9961d322ba5fc8077056dd8b/CMakeLists.txt#L22
需要改为：
```cmake
add_subdirectory(Extension/Lua)
```
(2)
https://github.com/KikoPlayProject/KikoPlay/blob/d0437da99436313f9961d322ba5fc8077056dd8b/CMakeLists.txt#L20
https://github.com/KikoPlayProject/KikoPlay/blob/d0437da99436313f9961d322ba5fc8077056dd8b/CMakeLists.txt#L101
以上其中一处需要加上`WebSockets`
```cmake
find_package(Qt5 COMPONENTS ... WebSockets REQUIRED)
```
(3)
https://github.com/KikoPlayProject/KikoPlay/blob/d0437da99436313f9961d322ba5fc8077056dd8b/CMakeLists.txt#L72-L83
https://github.com/KikoPlayProject/KikoPlay/blob/d0437da99436313f9961d322ba5fc8077056dd8b/CMakeLists.txt#L114-L118
以上其中一处需要加上`Qt::WebSockets`
```cmake
target_link_libraries(${PROJECT_NAME} 
PRIVATE 
    ...
    ...
    Qt::WebSockets
)
```

修改之后不需要用`vcpkg`，直接编译就能通过。
不过对于(2)和(3)，由于我只使用 Archlinux 所以不确定其他发行版是不是有同样问题，也不确定 windows 是不是也有同样的问题。不确定是否有必要修改，也不确定应该把修改放哪个位置，所以没有提交PR。

**Comment by madoka773** [comment]
aur不能用吗？

https://github.com/flathub/io.github.KikoPlayProject.KikoPlay

或者可以参考flatpak

**Comment by zerobikappa** [comment]
@madoka773 aur就是我在维护，用的是`qmake`编译，最近想试一下用`cmake`编译然后就发现有这个问题。

**Comment by Protostars** [comment]
可以提个mr，cmake相关配置我没有维护
