### ISSUE TITLE
能否修正一下“资源搜索”——“过滤”后结果放在同一页内。

### ISSUE THREAD

**Issue by merlin0531** [KikoPlayProject/KikoPlay#153]
![微信截图_20240417221839](https://github.com/KikoPlayProject/KikoPlay/assets/77084268/1d0eb9f4-3043-48b6-86dc-bb163322f46c)
能否修正一下“资源搜索”——“过滤”后结果放在同一页内。目前版本是一页内可能只有两三个结果，使用起来比较麻烦。

**Comment by Protostars** [comment]
这个目前做不到，因为脚本返回结果就是分页的，后面的结果可能还没获取到
