### ISSUE TITLE
弹幕加粗选项不是对所有弹幕都生效

### ISSUE THREAD

**Issue by BloodlineL** [KikoPlayProject/KikoPlay#154]
设定弹幕加粗后弹幕里大部分加粗，少部分还是细的
还有能不能考虑加个自动加载同名音轨的功能，类似自动加载同名xml弹幕那样

**Comment by Protostars** [comment]
可能是弹幕纹理缓存的缘故，等一段时间；
目前不考虑，你可以手动添加一下，下次播放能自动加载
