### ISSUE TITLE
Mac下brew install error

### ISSUE THREAD

**Issue by Lycoyas** [KikoPlayProject/KikoPlay#155]
Last 15 lines from /Users/bytedance/Library/Logs/Homebrew/kikoplay/14.make:
                 ^
/opt/homebrew/Cellar/qt@5/5.15.13/lib/QtWidgets.framework/Headers/qdialog.h:98:18: note: overridden virtual function is here
    virtual void reject();
                 ^
6 warnings generated.
/Library/Developer/CommandLineTools/usr/bin/clang++ -stdlib=libc++ -headerpad_max_install_names  -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -o KikoPlay.app/Contents/MacOS/KikoPlay logger.o notifier.o autodownloadmanager.o peermodel.o mediahandler.o animeinfo.o animeprovider.o episodeitem.o tagnode.o danmuprovider.o eventanalyzer.o mpvpreview.o simpleplayer.o bgmcalendarscript.o danmuscript.o libraryscript.o resourcescript.o scriptbase.o scriptmanager.o scriptmodel.o scriptsettingmodel.o addpool.o addrule.o aliasedit.o animedetailinfopage.o animesearch.o autodownloadwindow.o danmulaunch.o danmuview.o gifcapture.o inputdialog.o logwindow.o settings.o downloadpage.o lanserverpage.o mpvpage.o mpvshortcutpage.o scriptpage.o stylepage.o snippetcapture.o stylemanager.o backgroundfadewidget.o backgroundwidget.o clickslider.o colorpicker.o colorslider.o danmustatiswidget.o dialogtip.o fonticonbutton.o loadingicon.o main.o mainwindow.o framelesswindow.o bottomlayout.o rolllayout.o toplayout.o danmupool.o globalobjects.o playlist.o mpvplayer.o list.o player.o pooleditor.o framelessdialog.o localprovider.o adddanmu.o matcheditor.o selectepisode.o blocker.o blockeditor.o capture.o mediainfo.o common.o about.o network.o htmlparsersax.o animeitemdelegate.o librarywindow.o episodesmodel.o util.o aria2jsonrpc.o dirselectwidget.o downloaditemdelegate.o downloadmodel.o torrent.o downloadwindow.o adduritask.o selecttorrentfile.o poolmanager.o checkupdate.o flowlayout.o timelineedit.o lanserver.o httpserver.o playlistitem.o playlistprivate.o cacheworker.o danmurender.o danmumanager.o nodeinfo.o managermodel.o animeworker.o animemodel.o labelmodel.o animefilterproxymodel.o labelitemdelegate.o bgmlist.o bgmlistwindow.o ressearchwindow.o pool.o capturelistmodel.o captureview.o tip.o qrc_res.o moc_logger.o moc_notifier.o moc_autodownloadmanager.o moc_peermodel.o moc_mediahandler.o moc_animeprovider.o moc_episodeitem.o moc_danmuprovider.o moc_mpvpreview.o moc_simpleplayer.o moc_scriptmanager.o moc_scriptmodel.o moc_scriptsettingmodel.o moc_addpool.o moc_addrule.o moc_aliasedit.o moc_animedetailinfopage.o moc_animesearch.o moc_autodownloadwindow.o moc_danmulaunch.o moc_danmuview.o moc_gifcapture.o moc_inputdialog.o moc_logwindow.o moc_mainwindow.o moc_framelesswindow.o moc_danmupool.o moc_settings.o moc_downloadpage.o moc_lanserverpage.o moc_mpvpage.o moc_mpvshortcutpage.o moc_scriptpage.o moc_settingpage.o moc_stylepage.o moc_snippetcapture.o moc_stylemanager.o moc_backgroundfadewidget.o moc_backgroundwidget.o moc_clickslider.o moc_colorpicker.o moc_colorslider.o moc_danmustatiswidget.o moc_fonticonbutton.o moc_loadingicon.o moc_playlist.o moc_mpvplayer.o moc_list.o moc_player.o moc_pooleditor.o moc_framelessdialog.o moc_adddanmu.o moc_matcheditor.o moc_selectepisode.o moc_blocker.o moc_blockeditor.o moc_capture.o moc_mediainfo.o moc_about.o moc_animeitemdelegate.o moc_librarywindow.o moc_episodesmodel.o moc_aria2jsonrpc.o moc_dirselectwidget.o moc_downloaditemdelegate.o moc_downloadmodel.o moc_torrent.o moc_downloadwindow.o moc_adduritask.o moc_selecttorrentfile.o moc_poolmanager.o moc_checkupdate.o moc_timelineedit.o moc_lanserver.o moc_httpserver.o moc_cacheworker.o moc_danmurender.o moc_danmumanager.o moc_managermodel.o moc_animeworker.o moc_animemodel.o moc_labelmodel.o moc_animefilterproxymodel.o moc_labelitemdelegate.o moc_bgmlist.o moc_bgmlistwindow.o moc_ressearchwindow.o moc_pool.o moc_capturelistmodel.o moc_captureview.o moc_tip.o   -F/opt/homebrew/Cellar/qt@5/5.15.13/lib -L/opt/homebrew/opt/lua@5.3/lib -L/opt/homebrew/opt/mpv/lib -L/opt/homebrew/opt/qhttpengine/lib -L/usr/lib64/ -L/private/tmp/kikoplay-20240424-37942-v62eu1/KikoPlay-0.8.2/lib/x64/linux -L/private/tmp/kikoplay-20240424-37942-v62eu1/KikoPlay-0.8.2/lib64/linux -lmpv -lz -lm -llua5.3 -lqhttpengine -ldl -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtSql -framework QtNetwork -framework QtConcurrent -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
ld: warning: search path '/usr/lib64/' not found
ld: warning: search path '/private/tmp/kikoplay-20240424-37942-v62eu1/KikoPlay-0.8.2/lib/x64/linux' not found
ld: warning: search path '/private/tmp/kikoplay-20240424-37942-v62eu1/KikoPlay-0.8.2/lib64/linux' not found
Undefined symbols for architecture arm64:
  "GlobalObjects::normalFont", referenced from:
      MediaInfo::evalCommand(QList<QString>&, QList<MediaInfo::TextBlock>&) in mediainfo.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [KikoPlay.app/Contents/MacOS/KikoPlay] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/kikoplayproject/homebrew-kikoplay/issues

These open issues may also help:
Apple M1 brew install kikoplay make error https://github.com/KikoPlayProject/Homebrew-KikoPlay/issues/4

**Comment by Protostars** [comment]
这个太老了，提交它的人也不维护了，可以自行尝试一下编译最新版
