### ISSUE TITLE
希望弹幕池管理、编辑弹幕池界面不固定前台；编辑关联界面添加全选、添加网络弹幕界面批量复选

### ISSUE THREAD

**Issue by kagurainroy** [KikoPlayProject/KikoPlay#158]
![image](https://github.com/KikoPlayProject/KikoPlay/assets/22196444/70cdaedc-f69d-4d7b-ab82-8aa43a685b4d)

此处希望支持全选，AI-RAWS的日文标题文件经常不能自动识别

![image](https://github.com/KikoPlayProject/KikoPlay/assets/22196444/3d2542d1-12ea-4711-b2f7-e44e16361dae)

 此处希望可以简单的复选（按住拖动复选/按住shift复选之类），有些动画有一大堆SP、OP、ED什么的，直接全选的话还不如一个一个打勾

![image](https://github.com/KikoPlayProject/KikoPlay/assets/22196444/afdc34c1-8d40-4e5e-b599-198e517e663e)

![image](https://github.com/KikoPlayProject/KikoPlay/assets/22196444/3274076e-38f9-40b1-91b9-517051d0902a)

 此处和此处希望不要窗口置顶，调轴的话只能关了确认，打开改时轴，用起来很麻烦

**Comment by Protostars** [comment]
1. 全选在右键菜单里
2. 其他会考虑改进

**Comment by Protostars** [comment]
1.0.3做了改进，可以试试
