### ISSUE TITLE
ubuntu 22.04 编译失败 找不到 Lua.pro 

### ISSUE THREAD

**Issue by Gray-Stone** [KikoPlayProject/KikoPlay#159]
步骤：
* git clone 
* qmake build.pro
* make

错误内容

```
cd Extension/Lua/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/leogray/KikoPlay/Extension/Lua/Lua.pro ) && make -f Makefile 
Cannot find file: /home/leogray/KikoPlay/Extension/Lua/Lua.pro.
make: *** [Makefile:65: sub-Extension-Lua-make_first] Error 2
```

**Comment by Gray-Stone** [comment]
所以关键是这两行对吧
```
    ln -sf "${srcdir}/build-lua53/libmyLua53.a" "${srcdir}/KikoPlay/lib/x64/linux/liblua53.a"
    ln -sf "${srcdir}/build-lua53/libmyLua53.a" "${srcdir}/KikoPlay/Extension/Lua/liblua53.a"
```

我还是不是很确定怎么做。不过既然有flathub版本的，我就直接下载了。

**Comment by Gray-Stone** [comment]
ok 我折腾明白了。就是先 `cmake -B"${srcdir}/build-lua53"` 然后symlink过去。编译是成功了，现在遇到了segfault 是其它issue里面提到的。
flatpak 版本我主要碰到字体很奇怪。

**Comment by madoka773** [comment]
> ok 我折腾明白了。就是先 `cmake -B"${srcdir}/build-lua53"` 然后symlink过去。编译是成功了，现在遇到了segfault 是其它issue里面提到的。
> flatpak 版本我主要碰到字体很奇怪。

具体说说字体问题，或者在flatpak那里提个issue

**Comment by Gray-Stone** [comment]
> 具体说说字体问题，或者在flatpak那里提个issue

说实话我也不确定具体是哪一步搞定的。总而言之flatpat呢里有好几个字体的issue了。基本上问题在于系统的字体faltpak不一定都找得到。

我最后是吧一大堆字体直接塞到faltpak某些包的目录下面去。然后在kikoplay里面加了一行mpv的设置，选择某个特定的字体最为字幕。然后弹幕的字体也是塞进去之后手动设置了。但是设置完要重启kikoplay或者播放一段时间才会起效。
