### ISSUE TITLE
图标Logo

### ISSUE THREAD

**Issue by LuomingXu** [KikoPlayProject/KikoPlay#160]
可以换一个在不同背景下都"高可见"的图标吗?
在黑色背景下, 几乎不可见

![image](https://github.com/KikoPlayProject/KikoPlay/assets/24503603/80bc7088-a9a0-48cb-9e0b-9ed357aaf745)
![image](https://github.com/KikoPlayProject/KikoPlay/assets/24503603/e1d7966a-729f-463a-9f47-fcbf589b1178)

**Comment by Bianca2000** [comment]
![image](https://github.com/KikoPlayProject/KikoPlay/assets/58384118/eb43148b-ff73-4d86-8247-da9d9c9f61e3)
可以自己找個圖換

**Comment by Protostars** [comment]
有好的图标建议也可以提出来，我不擅长画图标
