### ISSUE TITLE
libmpv0.38版本中，窗口分离问题

### ISSUE THREAD

**Issue by ZSPAPAPA** [KikoPlayProject/KikoPlay#161]
OS: Debian sid
libmpv升级为0.38后，播放视频时窗口会分离为2个MPV和1个KikoPlay主窗口，视频在其中一个MPV中播放。
在参数设置里添加`vo=libmpv`后变为1个MPV，并且KikoPlay可以正常播放。
![1](https://github.com/KikoPlayProject/KikoPlay/assets/34394578/d14e317d-1169-48f1-90a0-946044e36537)

**Comment by Protostars** [comment]
下个版本会修复

**Comment by Protostars** [comment]
1.0.3已修复
