### ISSUE TITLE
【新功能请求】导出弹幕池相关

### ISSUE THREAD

**Issue by lanrene** [KikoPlayProject/KikoPlay#163]
### 需求一

每次导出弹幕的时候都会定位在 kiko 所在的文件夹，希望可以记住上次保存的文件夹

### 需求二

**需求说明**：

我喜欢把弹幕下载到本地，有少量剧可能第一次看的时候弹幕量很少，二刷的时候就需要把本地弹幕更新。
这时候痛点就出现了，我需要重新寻找视频 url 链接，回到 KikoPlay 添加网络弹幕，然后导出到本地覆盖原文件。

**期望实现**：

在导出的 XML 文件中添加一个保存视频 url 的标签，然后在需要更新的时候，可以直接像更新网络弹幕一样，直接点击 `🔄` 就可以更新本地弹幕了。

> 不知道直接修改本地文件能不能实现

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<i>
  <videourl>https://baidu.com</videourl>

  <d p="0,1,25,16777215,1603546627,0,1461426012,1461426012">...</d>
<i>
```

**Comment by Protostars** [comment]
1. 可以考虑
2. KikoPlay的设计就不是让用户频繁把弹幕导出到本地。KikoPlay自己有数据库记录每个弹幕池的信息，导出成xml很多信息就没有了，如果不是为了放到其他播放器里，不需要频繁导出到本地xml

**Comment by Protostars** [comment]
1.0.3针对第一个做了调整
