### ISSUE TITLE
【礼貌请教】可不可以通过用户提供cookie来获取b站全弹幕？

### ISSUE THREAD

**Issue by walltes** [KikoPlayProject/KikoPlay#165]
b站不登录只能获取到部分弹幕，那么可不可以由用户提供cookie调用b站[接口](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/danmaku/danmaku_proto.md#protobuf%E5%BC%B9%E5%B9%95)来获取全弹幕呢？

另：[biliplus](https://www.biliplus.com/)不需要用户提供cookie也可获取b站全弹幕

**Comment by Protostars** [comment]
这个是使用的弹幕接口不同，KikoPlay那个脚本用的是http://comment.bilibili.com/，只能获取那么多了

**Comment by walltes** [comment]
kikoplay那个脚本可不可以换个可以获取全弹幕的接口呢？

**Comment by Protostars** [comment]
我目前没时间改，你可以先自己试试
