### ISSUE TITLE
如何支持不同格式的xml文件？

### ISSUE THREAD

**Issue by kagurainroy** [KikoPlayProject/KikoPlay#166]
![image](https://github.com/KikoPlayProject/KikoPlay/assets/22196444/5143bf18-09dd-474a-9d5a-4fe2b0780ff6)
[ガールズバンドクライ　第8話　もしも君が泣くならば.zip](https://github.com/KikoPlayProject/KikoPlay/files/15443809/8.zip)
这是使用
https://github.com/koharubiyori/nicomment
导出的nicovideo弹幕，通过kikoplay无法正确加载，请问如何修改以支持？

**Comment by Protostars** [comment]
![图片](https://github.com/KikoPlayProject/KikoPlay/assets/20561421/4bcd96ce-40a3-4513-8e8a-2d82fa4abe7c)
KikoPlay支持的是类似b站的这种xml格式，`<d>`标签表示一条弹幕，弹幕的属性都在`p`属性里，以逗号分隔，分别是 时间、类型（滚动、顶部、底部）、大小、颜色、日期、<忽略>、发送人、<忽略>，解析过程参考`Play\Danmu\Provider\localprovider.cpp`
