### ISSUE TITLE
Linux Flatpak 升级至 1.0.3 版本后弹幕出现卡顿

### ISSUE THREAD

**Issue by yuntaz0** [KikoPlayProject/KikoPlay#172]
降级至之前的1.0.2版本(2024-06-09 07:59:02 +0000)后恢复正常

**Comment by Protostars** [comment]
看看是不是libmpv版本有变化

**Comment by yuntaz0** [comment]
对应的更新是“[Update libmpv and kikoplay module](https://github.com/flathub/io.github.KikoPlayProject.KikoPlay/pull/48)"，所以 libmpv 版本应该是变了0.37->0.38

**Comment by madoka773** [comment]
需要回到 0.38 吗

**Comment by yuntaz0** [comment]
可以让bot生成一个回到0.37的 test build，我试下能不能解决

**Comment by madoka773** [comment]
> 可以让bot生成一个回到0.37的 test build，我试下能不能解决

回 0.37 也行，flatpak 这方面很灵活

**Comment by yuntaz0** [comment]
那回 0.37 试试？

**Comment by madoka773** [comment]
> 那回 0.37 试试？

可以了，测试一下，我暂时没电脑

**Comment by yuntaz0** [comment]
测试 [Revert libmpv 0.37](https://github.com/flathub/io.github.KikoPlayProject.KikoPlay/pull/49) 后弹幕正常显示

**Comment by yuntaz0** [comment]
在9-17的更新之后MPV升级至0.38,再次出现相同的卡顿问题。

**Comment by pugaizai** [comment]
行吧那我再改回去

**Comment by yuntaz0** [comment]
感谢，确认修复

**Comment by pugaizai** [comment]
现在不升级mpv的话在 org.kde.Sdk//5.15-24.08 sdk编译不出来mpv了 @yuntaz0

**Comment by yuntaz0** [comment]
感谢，5.15-24.08 的版本我可以先试一下吗？

**Comment by pugaizai** [comment]
@yuntaz0 https://github.com/flathub/io.github.KikoPlayProject.KikoPlay/pull/72#issuecomment-2526406553

**Comment by yuntaz0** [comment]
这个版本（MPV0.39）没有出现卡顿问题
