### ISSUE TITLE
v1.0.3无法记住播放速度

### ISSUE THREAD

**Issue by LuomingXu** [KikoPlayProject/KikoPlay#178]
data/setting.ini
```ini
[Play]
PlaySpeed=1.7
```

![QQ_1721277305001](https://github.com/user-attachments/assets/babc9147-3048-4a47-9ad5-c2b547c1d681)
![QQ_1721277337770](https://github.com/user-attachments/assets/439862bc-d327-472d-82c3-867202842490)

**Comment by Protostars** [comment]
之后我确认一下是不是有bug

**Comment by Protostars** [comment]
刚刚修复了，可自行编译，也可到群里下载最新的可执行文件

**Comment by LuomingXu** [comment]
2e4cf7767578584dd84637249ca671c48620c10a solved
