### ISSUE TITLE
1.0.3获取webdav部分特定目录信息时会无响应，1.0.2则可以正常获取目录

### ISSUE THREAD

**Issue by walltes** [KikoPlayProject/KikoPlay#181]
1.0.3获取含有以下文件名文件时，程序会无响应，1.0.2则可以成功获取目录信息。
<img width="404" alt="msedge_EDIpTRtTQr" src="https://github.com/user-attachments/assets/1120a11e-8118-45a9-ba57-f66cfdcffa6c">
更改文件名后，1.0.3可以获取目录信息
![image](https://github.com/user-attachments/assets/01fcb4b7-d553-43c0-bf8b-396731d76cf4)

**Comment by Protostars** [comment]
已知问题，最新master做了修复，可以从群里下载编译好的最新可执行文件
