### ISSUE TITLE
播放列表 和 资料 的关联

### ISSUE THREAD

**Issue by LINKlang** [KikoPlayProject/KikoPlay#185]
kikoplay的播放列表里的和资料里的序号是没有关联的吗，我在资料里面改了番剧的序号，但是播放列表里的显示还是原来的序号
比如我有个第10集的视频被识别成EP2了，我在资料里改过来后播放列表还是显示的EP2而不是EP10

**Comment by LINKlang** [comment]
还有本地数据库也是，感觉跟无法修改一个，正常来说本地数据库不应该和资料同步吗

**Comment by Protostars** [comment]
播放列表和资料是独立的，基本过程是：播放列表关联弹幕池 → 添加识别的动画/ep到资料库
如果识别不正确，直接重新关联就好
