### ISSUE TITLE
读取本地弹幕时出现重复弹幕

### ISSUE THREAD

**Issue by cz-97** [KikoPlayProject/KikoPlay#190]
读取视频同文件夹内的同名xml，每个视频只对应了一个xml，xml文件中同一时刻没有重复弹幕，kikoplay读取后在弹幕列表中出现了重复弹幕，不是所有行和文件都会出现这种情况。xml来自蛋蛋play
![image](https://github.com/user-attachments/assets/7ce79313-7328-40ae-a31f-04217c28dc7d)

**Comment by Protostars** [comment]
看下弹幕池，有没有添加其他来源的弹幕，以及看下相同内容的弹幕，其他信息是否也相同

**Comment by cz-97** [comment]
> 看下弹幕池，有没有添加其他来源的弹幕，以及看下相同内容的弹幕，其他信息是否也相同

弹幕池里没有任何东西，相同的弹幕其他信息也相同。我把电脑上含有kikoplay的所有文件都删除后，重新下载了kikoplay，还是出现了这种现象，我换了从弹幕盒子网站下载的弹幕后就没有出现这种现象了。这个现象只在dandanplay下载的部分xml中出现过，在同一部番剧中也只有部分章节出现。

**Comment by cz-97** [comment]
[05.xml.txt](https://github.com/user-attachments/files/17956499/05.xml.txt)
这是会出现问题的xml

**Comment by Protostars** [comment]
我看了下，这个文件里本身有重复内容，你可以搜一下，比如`2006是15年前啊`

**Comment by cz-97** [comment]
好吧，我的问题，搜的时候没注意到
