### ISSUE TITLE
新开一贴，提些建议 

### ISSUE THREAD

**Issue by underlaw** [KikoPlayProject/KikoPlay#33]
kikoplay的ui及框架做的很漂亮，个人觉得应该是所有带aria2功能里最耐看的，框架采用动态拉伸，并支持记忆，很赞！

个人使用测试了一段时间，有以下反馈：

1、软件不能最小化到托盘，也就不能后台下载，这对长时间的BT下载来说，有点遗憾，望采纳增加此功能。

2、本软件下载完可删除.aria2控制文件，很不错文件夹清爽了不少。不知道是否能同时下载完也删除种子文件。

3、全局日志：RPC Reply Error: aria2.unpause都是以RPC Reply Error:开头，不知道是没优化好还是个人理解有误 :PRC回应错误。

4、aria2、mpv参数的设定，作者给的帮助文件说明不是很详细，比如aria2参数能否#注释，参数格式。如果作者大神时间充足或软件方便实现能否考虑各参数设置成下拉框选择形式 或者是复选框形式及文本框。

5、作者大神应该是个番控，哈哈。如果做成下载加播放功能的软件，建议能否关注一下别的视频下载，比如搜索功能脚本增加一些磁力搜索站的。上导航的资料一栏是否可设置成显示或隐藏。

6：推送到aria2:rpc设置成 http://127.0.0.1:6800/jsonrpc，推送失败，需要Token吗?

以上纯个人见解或偏好，供参考！谢谢

**Comment by Protostars** [comment]
1、个人一直感觉隐藏到托盘比较没用，因为我一般就下载一些新番之类的，时间不会太长。不过这个功能以后可以加上
2、删除.aria2文件是aria2自己的功能，如果没下完就不会删。记得应该有选项可以设置。删除种子文件倒是可以考虑
3、RPC Reply Error确实是aria2的rpc回应中出现错误，不过一般没什么问题
4、可以用#注释，和aria2的配置文件格式一样。选择太多，设置下拉框之类的挺麻烦，目前懒得弄
5、考虑到支持其他网站，搜索功能是以lua脚本的形式提供的，同时也希望有其他用户来贡献脚本。开发之初主要是考虑个人需求，希望能在一个软件内完成动画下载，建立资料档案，带弹幕的播放等功能，所以资料页目前暂时不会隐藏（不过看你好像主要用下载功能。。）
6、程序使用自带的aria2，启动时不为aria2的rpc设置token，正常情况下不会失败（至少目前我没遇到过）

**Comment by underlaw** [comment]
感谢回复，最小化这功能了，主要是下其它大的视频，不像番都比较小。

**Comment by underlaw** [comment]
删除正在下载的任务自动删除未完成的文件
下载错误自动删除未完成的文件
下载完成自动删除控制文件(.aria2后缀名文件)
下载完成自动删除种子文件(.torrent后缀名文件)
下载完成自动删除空目录
BT 下载完成自动清除垃圾文件(文件类型过滤功能)
BT 下载完成自动清除小文件(文件大小过滤功能)

提点。。。。建议嘿嘿

**Comment by Protostars** [comment]
0.8增加了：
 -最小化到托盘
 -自动清理种子文件
.aria2文件在任务完成后是会自动删除的，如果未完成（包括只选择了种子里的部分文件）就会保留
其他功能目前应该不会加入了
