### ISSUE TITLE
硬解支持

### ISSUE THREAD

**Issue by widsnoy** [KikoPlayProject/KikoPlay#38]
用MPV和KikoPlay播放同一个视频。
相同配置
```
hwdec=vaapi
```
而后者只能软解。

附上[日志](https://paste.ubuntu.com/p/N3h5JYYyMH/)

**Comment by Protostars** [comment]
似乎是没有加载成功：
```
[libmpv_render]v: Loading hwdec driver 'vaapi-egl'
[libmpv_render/vaapi-egl]v: VAAPI hwdec only works with OpenGL or Vulkan backends.
[libmpv_render]v: Loading failed.
```
KikoPlay里固定了vo=opengl-cb，不过我不确定这对硬解是否有影响，hwdec=auto能起作用吗？或者将KikoPlay的选项和MPV设置成一样看看

**Comment by widsnoy** [comment]
> 似乎是没有加载成功：
> 
> ```
> [libmpv_render]v: Loading hwdec driver 'vaapi-egl'
> [libmpv_render/vaapi-egl]v: VAAPI hwdec only works with OpenGL or Vulkan backends.
> [libmpv_render]v: Loading failed.
> ```
> 
> KikoPlay里固定了vo=opengl-cb，不过我不确定这对硬解是否有影响，hwdec=auto能起作用吗？或者将KikoPlay的选项和MPV设置成一样看看

是哪里的选项？设置里面的配置是一样的。hwdec=auto 也是一样的结果。

**Comment by Protostars** [comment]
0.8取消了固定vo=opengl-cb，你可以再试试
