### ISSUE TITLE
弹幕只能加载到120分钟？

### ISSUE THREAD

**Issue by xxhhlk** [KikoPlayProject/KikoPlay#39]
添加进去发现120分钟之后没有弹幕了，但是B站上是正常的，视频地址：https://www.bilibili.com/video/BV1gN411d7WK 没测试别的站的情况
版本是0.7.2
![Snipaste_2021-02-24_00-14-34](https://user-images.githubusercontent.com/15075327/108872701-6a146d80-7635-11eb-95cb-250f9fcbe0b8.png)

**Comment by Protostars** [comment]
弹幕接口的缘故，http://comment.bilibili.com/好像只能到120分钟

**Comment by xxhhlk** [comment]
啊这 那官方是怎么获取的 没法用相同方法获取吗

**Comment by Protostars** [comment]
0.8开始将弹幕功能通过外置脚本实现，有兴趣的用户可以自己写脚本试试
