### ISSUE TITLE
快捷键支持

### ISSUE THREAD

**Issue by dong-zeyu** [KikoPlayProject/KikoPlay#42]
MPV原生带有不少快捷键，是否可以直接将这些快捷键传递给后端，来获得原生的快捷键支持。自己常用的快捷键是 [ 和 ] 来调整速度

可以参考mpv的[文档](https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst)和[celluloid](https://github.com/celluloid-player/celluloid/blob/66e3a8b741ace53d2d4f386cab3785a960985ab0/src/celluloid-controller-input.c#L128)中的实现

**Comment by Protostars** [comment]
目前暂时没有计划支持，不过在不影响KikoPlay的快捷键的基础上，也欢迎其他人提交支持这一功能的代码
