### ISSUE TITLE
播放不了

### ISSUE THREAD

**Issue by yzceig** [KikoPlayProject/KikoPlay#43]
这两天在使用kikoplay时点击播放有时会卡住，然后win10提示退出或等待响应，点击退出后（这时任务管理器进程已关掉）双击电脑上其他视频使用其他播放器也都没反应，播放不了。然后重启win10会显示蓝屏重启提示。这种情况是硬盘问题还是程序相关系统进程问题，使用的是机械硬盘，一直使用kikoplay点击播放就会停顿一两秒。

**Comment by Protostars** [comment]
推测是解码方式的问题？设置`hwdec=no`
