### ISSUE TITLE
ArchLinux下弹幕来源为空

### ISSUE THREAD

**Issue by ling0412** [KikoPlayProject/KikoPlay#46]
OS：Archlinux 5.14.8-zen1-1-zen Gnome 41
版本:0.8.1 用AUR和自行make安装都试了一下，都有问题。
问题：添加文件夹后右键关联弹幕池一定会失败，在弹幕池中点击添加网络弹幕，没有一个来源。
![图片](https://user-images.githubusercontent.com/59282954/135798811-7c938753-79b5-4246-b38a-2e8822cd6302.png)
然后我用wine试了试windows的编译版本
同一视频文件，没有任何问题，直接匹配，添加网络弹幕中来源齐全
![图片](https://user-images.githubusercontent.com/59282954/135798292-bea12ba0-9fa1-4455-a4e0-60d664adf5a5.png)

**Comment by Protostars** [comment]
需要先准备脚本到合适位置  https://github.com/KikoPlayProject/KikoPlayScript

**Comment by ling0412** [comment]
我就是憨憨，问题解决了，谢谢。
