### ISSUE TITLE
全屏的时候右下角设置里的下拉选单无法修改

### ISSUE THREAD

**Issue by wdw89** [KikoPlayProject/KikoPlay#48]
全屏时右下角播放设置和弹幕设置里的下拉选单相关的设置无法修改，如播放速度、画面比例。
全屏的时候右上角会出现nvidia的标志，不知道是不是有影响

**Comment by Protostars** [comment]
这个全屏的问题，猜测是Qt自己的锅，要修改选项的话，先退回窗口模式吧
可以设置软解 hwdec=no 试试
