### ISSUE TITLE
使用内置的添加网络弹幕功能时只能加载3600条弹幕

### ISSUE THREAD

**Issue by kagurainroy** [KikoPlayProject/KikoPlay#49]
![image](https://user-images.githubusercontent.com/22196444/145815397-241cb674-bc42-4961-bbc2-ea747a003c34.png)
如图，第5、8集为本地xml弹幕，第1、2集为直接添加网络弹幕

**Comment by Protostars** [comment]
这个和脚本使用的bilibili接口相关，参考[这里](https://github.com/KikoPlayProject/KikoPlayScript/blob/c3aed2fc6d9e6e30f39fd39031c0b1298e2d3953/danmu/bilibili.lua#L288)，这个接口对于单个视频的弹幕量有限制，你可以自由修改脚本，或者过一段时间更新一次弹幕

**Comment by kagurainroy** [comment]
> 

请问下该怎么修改脚本呢= = 我不会编程来着，搜了下在bilibili.lua里没找到3600。。

**Comment by Protostars** [comment]
这是b站的限制，不是脚本的限制😂
