### ISSUE TITLE
无法下载搜索到的磁力链接

### ISSUE THREAD

**Issue by aoout** [KikoPlayProject/KikoPlay#51]
全局日志中有这样的输出。
![image](https://user-images.githubusercontent.com/60838705/148164362-52dc55fa-b03f-466e-ab7e-a114dcefa3dc.png)
随意选择了一些资源进行下载，都是这样。
![image](https://user-images.githubusercontent.com/60838705/148164491-ba909a15-c32e-4060-8a4f-0bebfa270009.png)
然而经过尝试发现下载功能对于普通链接是正常的。
复制搜索到的链接，用百度网盘离线下载，发现是可以的。
请问可能是什么样的原因造成了这样的异常呢？是我使用的方法有什么错误吗？应该如何解决呢？

**Comment by Protostars** [comment]
那些错误都不是什么问题，不用关心
得多加些tracker，不然aria2下载速度很慢的，旧种子很可能下不动，你可以试试新番的磁力链接
