### ISSUE TITLE
每次打开视频就错误

### ISSUE THREAD

**Issue by amronbook** [KikoPlayProject/KikoPlay#54]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/51790146/153149713-7b91ee17-ec53-42c1-9fda-660fb3af09fa.png">

**Comment by amronbook** [comment]
打开视频弹出来错误然后闪退怎么回事

**Comment by Protostars** [comment]
用的是最新版本吗，打开任意视频都有问题吗，可以把dmp文件发我看看

**Comment by amronbook** [comment]
是最新版本，不过我已经改用mpv了

**Comment by amronbook** [comment]
发不了dmp文件了，而且这个播放器播放视频时使用anime4k感觉我的风扇都特别热，但是使用mpv风扇吹出来的风就不热了，我也不清楚是怎么回事，就是kikoplay加载播放列表播放可以正常，但是双击视频文件打开就会报错

**Comment by amronbook** [comment]
是最新版本，的确mpv更快一些

**Comment by Protostars** [comment]
还是不能复现，试试下群里的0.8.2或者百度云的0.8.2，具体可以来群里交流

**Comment by amronbook** [comment]
我再下载一遍，看能不能复现

**Comment by amronbook** [comment]
我的电脑又复现了，型号联想r9000p，dmp文件怎么查看？kiko版本0.8.1

**Comment by Protostars** [comment]
0.8.2才是最新版本
