### ISSUE TITLE
能否把右上角的X功能优化下

### ISSUE THREAD

**Issue by underlaw** [KikoPlayProject/KikoPlay#58]
点X功能，能否做成后台，习惯点x最小化了 谢谢

**Comment by hooke007** [comment]
你完全可以reopen你的旧提案 https://github.com/KikoPlayProject/KikoPlay/issues/32

**Comment by Protostars** [comment]
后面会加上这个选项

**Comment by CL-Jeremy** [comment]
这个主要是跨平台有点麻烦：
1. GNOME 3 通知区域重写以后托盘图标不再显示，需要第三方插件
2. macOS 下，需要响应 Dock 图标点击，模仿多文档应用的交互逻辑
3. 另外还需要设计托盘图标本身是否常驻（是否在窗口还原后清除）
先写下个人一点想法，也许 Qt 自己有成熟的解决方案

**Comment by Protostars** [comment]
0.9.0已增加选项
