### ISSUE TITLE
弹幕有残影

### ISSUE THREAD

**Issue by wuwao1** [KikoPlayProject/KikoPlay#60]
版本:0.8.2
系统:win10
CPU: R5 3600
显卡: RX 580 2048SP
<img width="185" alt="1" src="https://user-images.githubusercontent.com/29857592/160272376-84b0efd8-1284-44a2-9c56-2468ec483b2d.png">

<img width="818" alt="12" src="https://user-images.githubusercontent.com/29857592/160272420-1d7afe8b-0d9f-4e2a-940f-a574b7357edb.png">

**Comment by Protostars** [comment]
可能是A卡的问题，参考这个 https://github.com/KikoPlayProject/KikoPlay/issues/12

**Comment by wuwao1** [comment]
same as https://github.com/KikoPlayProject/KikoPlay/issues/12
