### ISSUE TITLE
感觉少了批量功能啊，对大剧集不太友好

### ISSUE THREAD

**Issue by aDon0000** [KikoPlayProject/KikoPlay#63]
我140+集的金田一，一个个手动关联弹幕池，然后一个个关联弹幕，我哭死。
还是我不会操作？

**Comment by Protostars** [comment]
有批量功能，注意管理和添加弹幕窗口的右键菜单

**Comment by aDon0000** [comment]
都看了，都试了，搞不明白。。。有没有详细操作步骤

**Comment by aDon0000** [comment]
就把140个视频添加进同一个弹幕池已经搞晕我了

**Comment by Protostars** [comment]
关联：打开编辑关联窗口，选择bangumi来源搜索，选择动画，KikoPlay会自动把同一级的文件加到这个列表了，右键菜单全选，之后在第一项后点击“从当前分集顺序设置”，最后点击对话框的“√”确认就可以了
弹幕也是同理
基本逻辑是：一个视频关联到一个弹幕池，弹幕池里可以添加多个弹幕来源
操作并不复杂，你再试试，或者读一下说明文件

**Comment by aDon0000** [comment]
OK，弄懂了，添加弹幕窗口里的URL方式，有办法批量吗

**Comment by Protostars** [comment]
添加url目前还不能批量
