### ISSUE TITLE
请问可否增加字幕文件记忆与网络流播放功能

### ISSUE THREAD

**Issue by wangzy77** [KikoPlayProject/KikoPlay#66]
请问是否有增加这两个功能的计划：

1. 记忆播放视频时手动加载的外部字幕文件，并在下次播放时自动加载
2. 播放http等协议的网络流直播，m3u8格式等

非常感谢~

**Comment by Protostars** [comment]
1可以考虑，2预期不会，KikoPlay目前的定位还是本地视频播放器

**Comment by Protostars** [comment]
0.9.1支持记忆手动添加的字幕和音轨
