### ISSUE TITLE
网络无法连接

### ISSUE THREAD

**Issue by ws132** [KikoPlayProject/KikoPlay#67]
具体就是无法关联网络弹幕，无法查询番剧数据库
系统版本：win10 21H2
日志提示：
QSslSocket::connectToHostEncrypted: TLS initialization failed

**Comment by Protostars** [comment]
需要装一个vc(好像是2010?)的运行时，群里有

**Comment by ws132** [comment]
> 需要装一个vc（好像是2010？）的运行时，群里有

3Q，安装vc++2010已解决。
