### ISSUE TITLE
可不可以考虑打包成Flatapk或者Snap应用发布？

### ISSUE THREAD

**Issue by fenglingdingdang** [KikoPlayProject/KikoPlay#68]
来自一位被AUR构建报错折磨的Manjaro用户，使用通用打包方式就不用担心因为依赖或者其他原因引起的问题了

**Comment by Protostars** [comment]
linux是其他网友发布的，你要不尝试一下打包之后发布? 
(构建错误请确认将Lua submodule拉下来
