### ISSUE TITLE
希望能够自定义弹幕同屏上限，感谢开发者的不断更新。

### ISSUE THREAD

**Issue by cmy2019** [KikoPlayProject/KikoPlay#69]
说点题外话，之前用弹弹play挺长时间，但是很遗憾始终没解决弹幕掉帧和抖动这种基本的问题。
KikoPlay到目前已经做到很完美了，体验极好，十分感谢开发者的辛苦付出和开源精神！

**Comment by Protostars** [comment]
现在就能自定义同屏上限吧，弹幕设置里

**Comment by cmy2019** [comment]
> 现在就能自定义同屏上限吧，弹幕设置里

![屏幕截图(75)](https://user-images.githubusercontent.com/16515420/176065777-9296f80e-68e7-4d30-ad18-60fdb66e9753.png)
谢谢回复！现在同屏上限最低值是40，即使设置密集程度为无覆盖，当弹幕数量很大的时候还是会容易遮挡视频画面。

**Comment by Protostars** [comment]
0.9.1增加了区域控制
