### ISSUE TITLE
报错QSslSocket: TLS initialization Failed

### ISSUE THREAD

**Issue by RyougiShiki-214** [KikoPlayProject/KikoPlay#73]
![image](https://user-images.githubusercontent.com/53418317/180702426-8ad8f689-7fb1-4c68-93cc-97c49207be50.png)

![image](https://user-images.githubusercontent.com/53418317/180703518-1ad9bd21-816c-4188-b7fd-7985fb3df1a5.png)

系统是Win10 LTSC 2019
这个Qt论坛的帖子可能可以提供参考：https://forum.qt.io/topic/95700/qsslsocket-tls-initialization-failed

**Comment by Protostars** [comment]
装一个vc 2010 runtime

**Comment by RyougiShiki-214** [comment]
> 装一个vc 2010 runtime

Microsoft Visual C++ 2010  x64 Redistributable Setup 我在微软官网只找到了这个，不知道对不对

**Comment by Protostars** [comment]
> 

第一个

**Comment by RyougiShiki-214** [comment]
> > 
> 
> 第一个

解决了，谢谢！不过又出现了另外的问题，我新开一个Issue描述一下
