### ISSUE TITLE
LAN SERVER播放MKV只有音频流，没有视频流

### ISSUE THREAD

**Issue by RyougiShiki-214** [KikoPlayProject/KikoPlay#74]
本地端播放没有问题，问题仅出现在web端。

顺便问一下LAN SERVER是否可以修改端口号，谢谢

![image](https://user-images.githubusercontent.com/53418317/181485713-9c0a8a1a-129a-4526-a673-90fa1a831c38.png)

**Comment by Protostars** [comment]
可以在KikoPlay的设置里修改，先关闭lan server然后再修改

KikoPlay的局域网服务是一个标准的http服务器，播放不正常是浏览器不能支持

**Comment by Protostars** [comment]
可以在KikoPlay的设置里修改，先关闭lan server然后再修改

KikoPlay的局域网服务是一个标准的http服务器，播放不正常是浏览器不能支持

**Comment by hooke007** [comment]
现代浏览器有个大雷是普遍不支持hevc

**Comment by RyougiShiki-214** [comment]
查了一下，hevc浏览器播放的问题确实比较棘手，目前只能先转码再用了。
如果其他人也遇到同样的问题了的话，可以参考下这个：[开源解决方案](https://github.com/goldvideo/h265player)，不过非计算机相关专业的我暂时没折腾明白怎么用，得花时间研究一下。。

**Comment by hooke007** [comment]
支持hevc硬解的chrome104正式发布了

`--enable-features=PlatformHEVCDecoderSupport`

**Comment by RyougiShiki-214** [comment]
> 

Chrome这更新也太及时了，感谢告知！
