### ISSUE TITLE
LAN Server无法显示字幕

### ISSUE THREAD

**Issue by RyougiShiki-214** [KikoPlayProject/KikoPlay#77]
本地显示外挂ASS字幕正常，
![image](https://user-images.githubusercontent.com/53418317/183230721-6b40b9da-c765-4fb5-b3b4-0d821246d476.png)
网页端就不显示了
![image](https://user-images.githubusercontent.com/53418317/183231276-e75bd9b5-d3ba-46a8-8aec-78add5ba9fb8.png)

Chrome版本 104.0.5112.81（正式版本） （64 位

**Comment by Protostars** [comment]
网页功能比较弱，我记得好像不支持字幕? 你可以试试android端，也可以尝试把字幕转换成弹幕
