### ISSUE TITLE
能否新增高级弹幕播放功能(弹幕类型7)

### ISSUE THREAD

**Issue by Peter-JY** [KikoPlayProject/KikoPlay#81]
如题所述，在导入xml后将高级弹幕识别为一般弹幕

e.g.
`<d p="21.00000,7,38,16776960,1632892730,0,4454cc96,55470473021500928,10">[&#34;400&#34;,&#34;151&#34;,&#34;1-1&#34;,&#34;4&#34;,&#34;☆因为不是孤身一人☆&#34;,&#34;0&#34;,&#34;0&#34;,&#34;400&#34;,&#34;151&#34;,&#34;600&#34;,0,1,&#34;SimHei&#34;,1]</d> `
显示为
`[&#34;400&#34;,&#34;151&#34;,&#34;1-1&#34;,&#34;4&#34;,&#34;☆因为不是孤身一人☆&#34;,&#34;0&#34;,&#34;0&#34;,&#34;400&#34;,&#34;151&#34;,&#34;600&#34;,0,1,&#34;SimHei&#34;,1] `

**Comment by Protostars** [comment]
这种弹幕比较少，除了b站之外也不怎么能看到，我目前没有计划增加（预计未来一段时间也不会），（当然其他人贡献代码我是支持的😎
