### ISSUE TITLE
建议添加屏蔽彩色弹幕功能

### ISSUE THREAD

**Issue by Ling-collab** [KikoPlayProject/KikoPlay#83]
可以参考b站的一下功能，屏蔽彩色弹幕，弹幕区域显示，弹幕透明度等等

**Comment by Protostars** [comment]
支持屏蔽彩色弹幕的，在编辑屏蔽规则的右上角里选“颜色”，之后添加规则，屏蔽非白色弹幕即可，具体可以看看使用说明 

弹幕区域显示后续会增强 

弹幕透明度一开始就支持，弹幕外观里调整，不明白也可以看使用说明.pdf
