### ISSUE TITLE
Library脚本能不能加入豆瓣？

### ISSUE THREAD

**Issue by may349007** [KikoPlayProject/KikoPlay#86]
有一些较老的番剧在Bangumi找不到关联，无法使用弹幕。。希望能加入[豆瓣](https://movie.douban.com/)让资料库更齐全，谢谢

**Comment by may349007** [comment]
弹幕脚本也希望加入[异世界动漫](https://www.gqdm.net/)，弹幕站多多益善～

**Comment by Protostars** [comment]
已增加异世界动漫，豆瓣我目前不管了，有兴趣的人可以自行尝试
