### ISSUE TITLE
腾讯视频的弹幕接口有所改变？

### ISSUE THREAD

**Issue by gchust** [KikoPlayProject/KikoPlay#88]
小众软件介绍过来的，试用看看，发现添加腾讯视频的弹幕会报错
见 https://github.com/KikoPlayProject/KikoPlay/issues/87

看源码貌似之前的接口是 `http://bullet.video.qq.com/fcgi-bin/target/regist` ?
但是最新的接口应该是 https://dm.video.qq.com/barrage/segment/u00445z1gcx/t/v1/270000/300000 

这里有人写出过最新接口的弹幕下载脚本，不知道有没有人可以为这个项目适配下... https://github.com/yintuwanprojects/qqvideo-dm-scrape/blob/0991c004548720fa91fa23c26ede2caa7f61bf84/video_danmu.py

**Comment by Protostars** [comment]
赞，等下一个版本发布前会更新脚本

**Comment by Protostars** [comment]
已更新
