### ISSUE TITLE
可否添加弹幕出现行数或区域的限制功能？

### ISSUE THREAD

**Issue by may349007** [KikoPlayProject/KikoPlay#89]
有时过多的弹幕很影响观看体验，设透明度跟同屏上限不太够用，希望能跟弹弹play一样有这调整功能，能将弹幕限制在某个区块中。

另外弹弹play的脚本接口有变更：https://api.dandanplay.net/api/v2/
动画疯的弹幕脚本最近无法搜寻到东西，也希望能修复

**Comment by Protostars** [comment]
0.9.1会有这个功能，你也可以进群体验一下预览版

**Comment by Protostars** [comment]
已实现
