### ISSUE TITLE
那个新加入弹幕区域限制能不能再缩小点？

### ISSUE THREAD

**Issue by may349007** [KikoPlayProject/KikoPlay#92]
0.9.1版我有试用了，希望能再加个6分之1跟8分之1的选项，感谢更新

**Comment by may349007** [comment]
还有个问题，偶尔弹幕多时也会跨过设定好的区域限制。。

**Comment by Protostars** [comment]
1/6，1/8范围太小了，可能出不了几行弹幕
这个本身可能会有一点点误差，不重要
你应该配合弹幕数量，透明度来调整，实在觉得弹幕多，那关了弹幕吧

**Comment by may349007** [comment]
1／6应该是我的理想范围吧。而跨过区域的问题并不是只有一点误差，明明已设定了1／4，还是跑出几乎全屏的弹幕，不管重播几遍都是一样，固定那个位置的弹幕就是全屏跑出来，有确认过设定是卡在1／4的位置。大部分时间看是正常的，就是偶尔会有这状况

**Comment by Protostars** [comment]
你录个屏我看看吧

**Comment by may349007** [comment]
我刚又测试了一下，这好像是属于设定失效的问题，重新打开弹幕设定，先调高区域设定再改回1／4可以解决，可能是我电脑的问题造成的吧。。打扰了

**Comment by Protostars** [comment]
如果是能复现的bug可以反馈一下

**Comment by may349007** [comment]
确实是能复现，关闭KikoPlay再重开这问题就会出现，需要重新设定下弹幕区域才正常，其他选项重开似乎都运作正常，唯独这个有问题。

**Comment by Protostars** [comment]
修了一下，可以重新下载试试

**Comment by may349007** [comment]
修好了

**Comment by Protostars** [comment]
最新版本有个直播模式，你也可以试一试
