### ISSUE TITLE
ubuntu2204编译过不了

### ISSUE THREAD

**Issue by leoepoot** [KikoPlayProject/KikoPlay#94]
moc_scriptsettingmodel.o:moc_scriptsettingmodel.cpp:vtable for ScriptSettingModel: 错误: 对‘ScriptSettingModel::index(int, int, QModelIndex const&) const’未定义的引用
moc_scriptsettingmodel.o:moc_scriptsettingmodel.cpp:vtable for ScriptSettingModel: 错误: 对‘ScriptSettingModel::parent(QModelIndex const&) const’未定义的引用
moc_scriptsettingmodel.o:moc_scriptsettingmodel.cpp:vtable for ScriptSettingModel: 错误: 对‘ScriptSettingModel::rowCount(QModelIndex const&) const’未定义的引用
collect2: error: ld returned 1 exit status
make: *** [Makefile:974：KikoPlay] 错误 1

**Comment by Protostars** [comment]
`#include <QModelIndex>` 试试
