### ISSUE TITLE
Windows平台下全屏导致HDR失效，考虑在Windows平台使用DirectX API

### ISSUE THREAD

**Issue by Chaojimengnan** [KikoPlayProject/KikoPlay#96]
OpenGL渲染在Windows全屏模式下HDR会失效，具体请看 https://answers.microsoft.com/en-us/windows/forum/all/hdr-issue-in-gaming-on-windows-1110-all-versions/0be3d18f-9908-41c4-a870-b700b30781e6

可以考虑在Windows使用DirectX API并添加Direct API的弹幕实现

**Comment by Protostars** [comment]
目前换成dx不太现实，你试试在迷你模式下，把窗口拉到全屏大小效果正常吗

**Comment by Chaojimengnan** [comment]
效果正常，不过稍微麻烦了一些

**Comment by Protostars** [comment]
后面或许会加一个选项，允许以这种方式来实现全屏

**Comment by hooke007** [comment]
mpv 的 render api 不是强制opengl吗，dx根本没法实现啊

**Comment by Chaojimengnan** [comment]
不太清楚，没用过libmpv。如果强制opengl的话，只能等微软修复这个HDR的问题了

**Comment by hooke007** [comment]
kiko用的是libmpv的render api, 这个东西实质的开发已经停止多年，仅有opengl后端可用
转向wid才能支持vo=gpu 或者gpu-next这些现代的东西，工作量可能等于重新开发了
