### ISSUE TITLE
aria2进程冲突

### ISSUE THREAD

**Issue by UmbraNix** [KikoPlayProject/KikoPlay#98]
我本身也在用本地的aria2作为下载工具，打开kikoplay后会把我自己的进程冲掉，再关闭kikoplay后就没有开着的aria2了，想问一下有没有什么解决的办法

**Comment by Protostars** [comment]
目前没有开关，你可以把几行注释之后重新编译
https://github.com/KikoPlayProject/KikoPlay/blob/master/Download/aria2jsonrpc.cpp#L14

**Comment by Protostars** [comment]
增加了开关`Download/KillExistAria2`，可在`settings.ini`中手动设置，默认为true，改成false就不会在启动时结束aria2进程了

**Comment by UmbraNix** [comment]
感谢作者
heartheartheartheart

**Comment by FxxKZhangYue** [comment]
> 增加了开关`Download/KillExistAria2`，可在`settings.ini`中手动设置，默认为true，改成false就不会在启动时结束aria2进程了

[Download]
KillExistAria2=false

改成false仍然会关闭aria2
